// src/app/components/header/header.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrl: './header.component.css',
})
export class HeaderComponent {
  @Input() menu: any;
  @Input() selected = 0;
  @Input() isEl = true;

  @Output() categoryClick = new EventEmitter<number>();
  @Output() languageToggle = new EventEmitter<boolean>();
  @Output() menuToggle = new EventEmitter<boolean>();

  readonly logo = 'images/header/s_logo.png';
  readonly elFlag = 'images/flags/s_eflag.png';
  readonly enFlag = 'images/flags/s_gflag.png';
  readonly langIcon = 'images/icons/general/language.png';
  readonly menuIcon = 'images/icons/general/menu.png';

  onCategoryClick(index: number): void {
    this.categoryClick.emit(index);
  }

  onLanguageToggle(): void {
    this.languageToggle.emit(this.isEl);
  }

  onMenuToggle(event: Event): void {
    const checked = (event.target as HTMLInputElement).checked;
    this.menuToggle.emit(checked);
  }
}

<div class="mainHeaderContainer">
  <div class="topHeader">
    <div class="headerSwitchContainer">
      <img alt="menu" [src]="menuIcon" style="height: 40px; width: auto;">
      <label class="switch-toggle">
        <input
          class="switch-toggle__input"
          type="checkbox"
          [checked]="menu?.isRest"
          (change)="onMenuToggle($event)"
        >
        <span class="switch-toggle__slider"></span>
      </label>
    </div>

    <img alt="logo" class="imageL" [src]="logo">

    <div class="headerLanguageCont" (click)="onLanguageToggle()">
      <img alt="language" [src]="langIcon" style="height: 20px; width: auto; margin-right: 20px;">
      <img
        alt="language flag"
        [src]="isEl ? elFlag : enFlag"
        style="height: 1.5vh; width: auto;"
      >
    </div>
  </div>

  <div class="headerLevTwo">
    <div *ngFor="let category of menu?.categories; index as i" style="display: flex; align-items: center;">
      <div
        class="categoryHeaderContainer"
        [class.selected]="selected === i"
        (click)="onCategoryClick(i)"
      >
        {{ category.title }}
      </div>
      <img alt="" [src]="category.icon" style="height: 25px; width: auto; margin-right: 10px;">
    </div>
  </div>
</div>

// src/Pages/Home/Header.jsx
import React, { useState } from "react";
import logo from "./../../images/header/s_logo.png";
import el_flag from "./../../images/flags/s_eflag.png";
import en_flag from "./../../images/flags/s_gflag.png";
import "./Header.css";



function Header({ menu, clicked, selected , switchLang,isEl}) {
    
   
    const innerSwitch = (value)=>{
        switchLang(value);
       console.log("edede");
    }
    
    
    return (
        <div className="mainHeaderContainer">
            <img alt="problem loading" className="imageL" src={logo}></img>
            
            <div className="headerLevTwo">
                {menu.categories.map((categorie, i) => (
                    <div style={{display:"flex",alignItems:"center"}}>
                    <div
                        key={i}
                        onClick={(e) => {
                            clicked(e.target.id);
                        }}
                        className={selected === i ? "categoryHeaderContainer selected" : "categoryHeaderContainer"}
                        id={i}
                    >
                        {categorie.title}
                         
                    </div>
                    <img style={{height:"25px",width:"auto",marginRight:"10px"}} src={categorie.icon} ></img>
                     </div>
                    
                ))}
            </div>
            
            
        </div>
    );
}

export default Header;
