// src/Pages/Category/Category.jsx
import React from "react";
import Product from "../Product/Product";
import "./Category.css";

function Category({ category ,addMargin}) {
    return (
        <div className={`categoryContainer ${addMargin&&"extraMargin"} `}>
            <div className="headerContainer">
                <span className="title">{category.title}</span>
                <img alt="" style={{marginLeft:"20px",height:"35px",width:"auto"}} src={category.icon}></img>
                
            </div>
            <div className="line"></div>
            <div className="productsContainer">
                {category.products.map((product, i,a) => (
                    <Product key={i} sera={i} array={a} product={product} />
                ))}
            </div>
        </div>
    );
}

export default Category;

// src/app/components/category/category.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-category',
  templateUrl: './category.component.html',
  styleUrl: './category.component.css',
})
export class CategoryComponent {
  @Input() category: any;
  @Input() addMargin = false;
}

<div class="categoryContainer" [class.extraMargin]="addMargin">
  <div class="headerContainer">
    <span class="title">{{ category?.title }}</span>
    <img alt="" [src]="category?.icon" style="margin-left: 20px; height: 35px; width: auto;">
  </div>
  <div class="line"></div>
  <div class="productsContainer">
    <app-product
      *ngFor="let product of category?.products; index as i; let last = last"
      [product]="product"
      [isLast]="last"
    ></app-product>
  </div>
</div>
