// src/Pages/Product/Product.jsx
import React from "react";
import "./Product.css";

function Product({ product, sera, array }) {
  return (
    <div
      className={sera === array.length - 1 ? "productCont last" : "productCont"}
    >
      <div className="productInfo">
        
          <span className="productTitle">{product.title}</span>
      
        {product.desc != "" && <span className="productDesc">{product.desc}</span> }
          <span className="productPrice">{product.price}</span>
      </div>
      <div className="productPhotoCont">
        {product.photo && product.isVideo !== true ? (
          <img
            alt="error"
            id={sera}
            loading="lazy"
            className="productPhoto"
            src={product.photo}
          ></img>
        ) : product.isVideo ? (
          <video
            playsInline
            id={sera}
            muted
            autoPlay
            loop
            className="productPhoto"
            src={product.photo}
          ></video>
        ) : (
          <></>
        )}
      </div>
    </div>
  );
}

export default Product;

// src/app/components/product/product.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-product',
  templateUrl: './product.component.html',
  styleUrl: './product.component.css',
})
export class ProductComponent {
  @Input() product: any;
  @Input() isLast = false;
}

<div class="productCont" [class.last]="isLast">
  <div class="productInfo">
    <span class="productTitle">{{ product?.title }}</span>
    <span *ngIf="product?.desc !== ''" class="productDesc">{{ product?.desc }}</span>
    <span class="productPrice">{{ product?.price }}</span>
  </div>

  <div class="productPhotoCont">
    <img
      *ngIf="product?.photo && product?.isVideo !== true"
      alt=""
      loading="lazy"
      class="productPhoto"
      [src]="product?.photo"
    >
    <video
      *ngIf="product?.isVideo"
      playsinline
      muted
      autoplay
      loop
      class="productPhoto"
      [src]="product?.photo"
    ></video>
  </div>
</div>
