// src/Pages/Home/Home.jsx
//DEPNDENCIES
import React, { useState } from "react";

//CSS
import "./Home.css";

//COMPONENTS
import Menu from "./../../Utils/Menu";
import Header from "./Header";
import Category from "../Category/Category";
import { Switch } from "@mui/material";

//IMAGES
import bg from "./../../images/header/s_bg.jpg";
import logo from "./../../images/header/logo.png";
import el_flag from "./../../images/flags/s_eflag.png";
import en_flag from "./../../images/flags/s_gflag.png";

//icons
import menu_icon from "./../../images/icons/general/menu.png"
import lang_icon from "./../../images/icons/general/language.png"
import info_icon from "./../../images/info.png"
import close_icon from "./../../images/close.png"
import fb_icon from "./../../images/facebook.png"
import insta_icon from "./../../images/instagram.png"
import google_icon from "./../../images/googlemaps.png"
import taxi_icon from "./../../images/taxi.png"
import reserve_icon from "./../../images/reserve.png"
import sunbed_icon from "./../../images/sunbed.png"
function Home({ setPro, pro }) {
    const [levelOne, setLevelOne] = useState(false);
    const [levelTwo, setLevelTwo] = useState(false);
    const [selectedCategory, setSelectedCategory] = useState(0);
    const [menu, setMenu] = useState(new Menu("el", false));
    const [isEl, setIsEl] = useState(true);
    const [show, setShow] = useState(true);
    const [infoShow,setInfoShow] = useState(false);
   


    const switchLang = (value) => {
        if (value) {
            setMenu(new Menu("en", menu.isRest));
            setIsEl(false);
        } else {
            setMenu(new Menu("el", menu.isRest));
            setIsEl(true);
        }
    };

    const clicked = (i) => {
        let y = getPos(document.getElementsByClassName("categoryContainer")[i]).y;
        const offset = window.innerWidth / 6;
        document.getElementsByClassName("outerContainer")[0].scrollTo({ top: y + offset, behavior: "smooth" });
        setSelectedCategory(i);
    };
    function getPos(el) {
        for (var lx = 0, ly = 0; el != null; lx += el.offsetLeft, ly += el.offsetTop, el = el.offsetParent);
        return { x: lx, y: ly };
    }
    
    const onScroll = (e) => {
        setShow(false);
        const point1 = window.innerWidth / 2 - 80;
        const point2 = window.innerWidth / 2 + 20;
        const scroll = e.target.scrollTop;
        const categories = document.getElementsByClassName("categoryContainer");

        if (point1 < scroll && scroll < point2) {
            setLevelOne(true);
            setInfoShow(false);
        } else {
            setLevelOne(false);
        }

        if (point2 < scroll) {
            setLevelTwo(true);
        } else {
            setLevelTwo(false);
        }
        
        for (let i = categories.length - 1; i >= 0; i--) {
            if (getPos(categories[i]).y < scroll) {
                
                let x = getPos(document.getElementsByClassName("categoryHeaderContainer")[i]).x;
                document.getElementsByClassName("headerLevTwo")[0]?.scrollTo({ behavior: "smooth", left: x - 50 });
                setSelectedCategory(i);
                break;
            }
        }
    };
    const changed = (e) => {
        setMenu(new Menu(isEl ? "el" : "en", e.target.checked));
        
    };

    return (
        <div className="Main">
            <img alt="problem" src={info_icon} onClick={()=>{
                if(infoShow){
                    document.getElementById("info").classList.remove("moveIn");
                    document.getElementById("info").classList.add("moveOut");
                    setTimeout(()=>{setInfoShow(!infoShow)},1000)
                }else
                setInfoShow(!infoShow);
                
                }} className="info" ></img>
            {show && (
                <div className="modalContainer">
                    <div style={{ width: "100%", textAlign: "center" }}>
                    
                        <div style={{ width: "100%", display: "flex", justifyContent: "space-evenly",alignItems:"center", marginTop: "10px" }}>
                            <img
                                alt="problem loading"
                                style={{ height: "10vw", width: "auto" }}
                                src={en_flag}
                                onClick={() => {
                                    switchLang(false);
                                }}
                            ></img>
                            <img alt="error" src={lang_icon}  style={{height:"40px",width:"auto"}}></img>
                            <img
                                alt="problem loading"
                                style={{ height: "10vw", width: "auto" }}
                                src={el_flag}
                                onClick={() => {
                                    switchLang(true);
                                }}
                            ></img>
                        </div>
                    </div>
                    <div style={{ height: "30%", width: "100%", textAlign: "center", display: "flex", flexDirection: "column", justifyContent: "space-between", alignItems: "center" }}>
                        <button
                        style={{display:"flex",justifyContent:"center",alignItems:"center"}}
                            className="buttonModal"
                            onClick={() => {
                                changed({ target: { checked: true } });
                                setShow(false);
                            }}
                        >
                            <img alt="error" style={{height:"30px",width:"auto"}} src={menu_icon} ></img>
                            {isEl ? "Εστιατορίου" : "Restaurant"}
                        </button>
                        <button
                        style={{display:"flex",justifyContent:"center",alignItems:"center"}}
                            className="buttonModal"
                            onClick={() => {
                                changed({ target: { checked: false } });
                                setShow(false);
                            }}
                        >
                            <img alt="error" style={{height:"30px",width:"auto"}} src={menu_icon} >
                            </img>
                            {isEl ? "Παραλίας" : "Beach"}
                        </button>
                    </div>

                    <button
                        className="buttonModal"
                        style={{ color: "black" }}
                        onClick={() => {
                            setShow(false);
                        }}
                    >
                        {!isEl ? "Close" : "Κλείσιμο"}
                    </button>
                </div>
            )}

            {
                infoShow&&
                <div id="info" className="infoCont moveIn">
                    <img
                        alt="problem" 
                        onClick={()=>{
                        document.getElementById("info").classList.remove("moveIn");
                        document.getElementById("info").classList.add("moveOut");
                        setTimeout(()=>{setInfoShow(false)},1000)
                    }} src={close_icon} className="closeIcon" ></img>
                    <a href="tel:+306937604194" >
                        <img src={reserve_icon} className="reserve_icon" ></img>
                    </a>
                    
                    <img src={sunbed_icon} className="sun_icon" ></img>
                    
                    
                    <div className="taxi_cont">
                        <img src={taxi_icon} className="taxi_icon" ></img>
                        <a href="tel:+306972429568">CLICK TO CALL</a>
                    </div>

                    
                    <div className="social_cont">
                        <a target="_blank" href="https://web.facebook.com/glysteriskopelos" >
                            <img src={fb_icon} className="social_icon" ></img>
                        </a>
                        <a target="_blank" href="https://www.instagram.com/glysteribeachbar/" >
                            <img src={insta_icon} className="social_icon" ></img>
                        </a>
                        <a target="_blank" href="https://goo.gl/maps/EJ2KNv4JvEXsi8128" >
                            <img src={google_icon}  className="social_icon" ></img>
                        </a>
                    </div>
                </div>
            }


           

            <div className="header">
                <img alt="error" style={{ borderBottomLeftRadius: "20px", borderBottomRightRadius: "20px" }} src={bg} className="bgim" />
                <img alt="error" src={logo} className="logoImg" />
            </div>
            {levelOne && (
                <div className="headerLevOne">
                    <img alt="error" src={logo} className="logoInHeader" />
                </div>
            )}
            {levelTwo && <Header menu={menu} clicked={clicked} selected={selectedCategory} switchLanguege={switchLang} switchMenu={changed} isEl={isEl}/>}

            <div  onScroll={onScroll} className="outerContainer">
                <div className="menu">
                    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", width: "80%" }}>

                        <div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}} >
                            <Switch onChange={changed} color="primary"  checked={menu.isRest}/>
                            <img alt="error" style={{height:"40px",width:"auto"}} src={menu_icon} ></img>
                            <span id="gg" style={{marginLeft:"15px"}} >
                                {!isEl ? `${menu.isRest ? "Beach" : "Restaurant"}` : `${menu.isRest ? "Παραλιας" : "Εστιατοριου"}`}
                            </span>
                        </div>
                        
                        <div 
                            style={{display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center"}} 
                            onClick={() => {
                                switchLang(isEl);
                            }}
                        >
                            <img alt="error" style={{height:"30px",width:"auto",marginRight:"10px"}}  src={lang_icon} ></img>
                            {!isEl ? (
                                <img
                                    alt="problem loading"
                                    style={{ height: "2.2vh", width: "auto" }}
                                    src={en_flag}
                                    
                                ></img>
                            ) : (
                                <img
                                    alt="problem loading"
                                    style={{ height: "2.2vh", width: "auto" }}
                                    src={el_flag}
                                    
                                ></img>
                            )}
                            
                        </div>
                        
                    </div>

                    {menu.categories.map((category, i) => {
                        return <Category id={"c" + i} key={i} category={category} setPro={setPro} addMargin={i===0 && levelTwo} />;
                    })}
                </div>
            </div>
        </div>
    );
}

export default Home;

// src/app/pages/home/home.component.ts
import { Component, ElementRef, ViewChild } from '@angular/core';

import Menu from '../../../Utils/Menu';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrl: './home.component.css',
})
export class HomeComponent {
  @ViewChild('outerContainer') outerContainerRef?: ElementRef<HTMLDivElement>;

  levelOne = false;
  levelTwo = false;
  selectedCategory = 0;
  menu = new Menu('el', false);
  isEl = true;
  show = true;
  infoShow = false;
  infoAnimatingOut = false;

  readonly bg = 'images/header/s_bg.jpg';
  readonly closeIcon = 'images/close.png';
  readonly fbIcon = 'images/facebook.png';
  readonly googleIcon = 'images/googlemaps.png';
  readonly logo = 'images/header/logo.png';
  readonly elFlag = 'images/flags/s_eflag.png';
  readonly enFlag = 'images/flags/s_gflag.png';
  readonly infoIcon = 'images/info.png';
  readonly instaIcon = 'images/instagram.png';
  readonly langIcon = 'images/icons/general/language.png';
  readonly menuIcon = 'images/icons/general/menu.png';
  readonly reserveIcon = 'images/reserve.png';
  readonly sunbedIcon = 'images/sunbed.png';
  readonly taxiIcon = 'images/taxi.png';

  switchLang(value: boolean): void {
    if (value) {
      this.menu = new Menu('en', this.menu.isRest);
      this.isEl = false;
      return;
    }

    this.menu = new Menu('el', this.menu.isRest);
    this.isEl = true;
  }

  clicked(index: number): void {
    const categories = document.getElementsByClassName('categoryContainer');
    const element = categories.item(index) as HTMLElement | null;

    if (!element || !this.outerContainerRef) {
      return;
    }

    const y = this.getPos(element).y;
    const offset = window.innerWidth / 6;

    this.outerContainerRef.nativeElement.scrollTo({
      top: y + offset,
      behavior: 'smooth',
    });

    this.selectedCategory = index;
  }

  getPos(el: HTMLElement | null): { x: number; y: number } {
    let lx = 0;
    let ly = 0;
    let current = el;

    while (current) {
      lx += current.offsetLeft;
      ly += current.offsetTop;
      current = current.offsetParent as HTMLElement | null;
    }

    return { x: lx, y: ly };
  }

  onScroll(event: Event): void {
    const target = event.target as HTMLElement;
    const point1 = window.innerWidth / 2 - 80;
    const point2 = window.innerWidth / 2 + 20;
    const scroll = target.scrollTop;
    const categories = document.getElementsByClassName('categoryContainer');

    this.show = false;

    if (point1 < scroll && scroll < point2) {
      this.levelOne = true;
      this.infoShow = false;
      this.infoAnimatingOut = false;
    } else {
      this.levelOne = false;
    }

    this.levelTwo = point2 < scroll;

    for (let i = categories.length - 1; i >= 0; i -= 1) {
      const category = categories.item(i) as HTMLElement | null;

      if (category && this.getPos(category).y < scroll) {
        const header = document.getElementsByClassName('categoryHeaderContainer').item(i) as HTMLElement | null;
        const headerLevelTwo = document.getElementsByClassName('headerLevTwo').item(0) as HTMLElement | null;
        const x = header ? this.getPos(header).x : 0;

        headerLevelTwo?.scrollTo({
          behavior: 'smooth',
          left: x - 50,
        });

        this.selectedCategory = i;
        break;
      }
    }
  }

  changed(checked: boolean): void {
    this.menu = new Menu(this.isEl ? 'el' : 'en', checked);
  }

  toggleInfo(): void {
    if (this.infoShow) {
      this.closeInfo();
      return;
    }

    this.infoAnimatingOut = false;
    this.infoShow = true;
  }

  closeInfo(): void {
    this.infoAnimatingOut = true;

    window.setTimeout(() => {
      this.infoShow = false;
      this.infoAnimatingOut = false;
    }, 1000);
  }
}

<div class="Main">
  <img alt="info" [src]="infoIcon" (click)="toggleInfo()" class="info">

  <div *ngIf="show" class="modalContainer">
    <div style="width: 100%; text-align: center;">
      <div
        style="width: 100%; display: flex; justify-content: space-evenly; align-items: center; margin-top: 10px;"
      >
        <img
          alt="english"
          style="height: 10vw; width: auto;"
          [src]="enFlag"
          (click)="switchLang(false)"
        >
        <img alt="language" [src]="langIcon" style="height: 40px; width: auto;">
        <img
          alt="greek"
          style="height: 10vw; width: auto;"
          [src]="elFlag"
          (click)="switchLang(true)"
        >
      </div>
    </div>

    <div
      style="height: 30%; width: 100%; text-align: center; display: flex; flex-direction: column; justify-content: space-between; align-items: center;"
    >
      <button
        style="display: flex; justify-content: center; align-items: center;"
        class="buttonModal"
        (click)="changed(true); show = false"
      >
        <img alt="menu" style="height: 30px; width: auto;" [src]="menuIcon">
        {{ isEl ? "Εστιατορίου" : "Restaurant" }}
      </button>

      <button
        style="display: flex; justify-content: center; align-items: center;"
        class="buttonModal"
        (click)="changed(false); show = false"
      >
        <img alt="menu" style="height: 30px; width: auto;" [src]="menuIcon">
        {{ isEl ? "Παραλίας" : "Beach" }}
      </button>
    </div>

    <button class="buttonModal" style="color: black;" (click)="show = false">
      {{ isEl ? "Κλείσιμο" : "Close" }}
    </button>
  </div>

  <div
    *ngIf="infoShow || infoAnimatingOut"
    id="info"
    class="infoCont"
    [class.moveIn]="infoShow && !infoAnimatingOut"
    [class.moveOut]="infoAnimatingOut"
  >
    <img alt="close" (click)="closeInfo()" [src]="closeIcon" class="closeIcon">
    <a href="tel:+306937604194">
      <img alt="reserve" [src]="reserveIcon" class="reserve_icon">
    </a>

    <img alt="sunbeds" [src]="sunbedIcon" class="sun_icon">

    <div class="taxi_cont">
      <img alt="taxi" [src]="taxiIcon" class="taxi_icon">
      <a href="tel:+306972429568">CLICK TO CALL</a>
    </div>

    <div class="social_cont">
      <a target="_blank" rel="noreferrer" href="https://web.facebook.com/glysteriskopelos">
        <img alt="facebook" [src]="fbIcon" class="social_icon">
      </a>
      <a target="_blank" rel="noreferrer" href="https://www.instagram.com/glysteribeachbar/">
        <img alt="instagram" [src]="instaIcon" class="social_icon">
      </a>
      <a target="_blank" rel="noreferrer" href="https://goo.gl/maps/EJ2KNv4JvEXsi8128">
        <img alt="maps" [src]="googleIcon" class="social_icon">
      </a>
    </div>
  </div>

  <div class="header">
    <img
      alt="background"
      [src]="bg"
      class="bgim"
      style="border-bottom-left-radius: 20px; border-bottom-right-radius: 20px;"
    >
    <img alt="logo" [src]="logo" class="logoImg">
  </div>

  <div *ngIf="levelOne" class="headerLevOne">
    <img alt="logo" [src]="logo" class="logoInHeader">
  </div>

  <app-header
    *ngIf="levelTwo"
    [menu]="menu"
    [selected]="selectedCategory"
    [isEl]="isEl"
    (categoryClick)="clicked($event)"
    (languageToggle)="switchLang($event)"
    (menuToggle)="changed($event)"
  ></app-header>

  <div #outerContainer (scroll)="onScroll($event)" class="outerContainer">
    <div class="menu">
      <div style="display: flex; justify-content: space-between; align-items: center; width: 80%;">
        <div style="display: flex; justify-content: space-between; align-items: center;">
          <label class="switch-toggle">
            <input
              class="switch-toggle__input"
              type="checkbox"
              [checked]="menu.isRest"
              (change)="changed($any($event.target).checked)"
            >
            <span class="switch-toggle__slider"></span>
          </label>
          <img alt="menu" style="height: 40px; width: auto;" [src]="menuIcon">
          <span id="gg" style="margin-left: 15px;">
            {{ !isEl ? (menu.isRest ? "Beach" : "Restaurant") : (menu.isRest ? "Παραλιας" : "Εστιατοριου") }}
          </span>
        </div>

        <div
          style="display: flex; flex-direction: column; align-items: center; justify-content: center;"
          (click)="switchLang(isEl)"
        >
          <img alt="language" style="height: 30px; width: auto; margin-right: 10px;" [src]="langIcon">
          <img
            alt="language flag"
            style="height: 2.2vh; width: auto;"
            [src]="isEl ? elFlag : enFlag"
          >
        </div>
      </div>

      <app-category
        *ngFor="let category of menu.categories; index as i"
        [category]="category"
        [addMargin]="i === 0 && levelTwo"
      ></app-category>
    </div>
  </div>
</div>
